spring.application.name=unit06-spring-boot

# Container 起動時の APP_MESSAGE を Spring Boot の設定値として利用する。
# Environment Variable が未指定の場合は右側の Default 値を使用する。
app.message=${APP_MESSAGE:Hello from Spring Boot}
